---
title: "emvs"
author: "zhuofan"
date: '2022-09-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Data generation
```{r}
set.seed(1)
n = 100
p = 4
x = matrix(NA,p,n)
x[1,] = rnorm(n)
x[2,] = rnorm(n)
x[3,] = 0.8*x[1,]+0.5*x[2,]+rnorm(100,0,0.1)
x[4,] = 0.9*x[1,]+0.9*x[3,]-0.5*x[2,]+rnorm(100,0,0.1)
beta0 = matrix(c(1,0,0.8,0.9,0,1,0.5,-0.5,0,0,0,0.9,0,0,0,0),p,p)
plot(x[3,],x[1,])

```
## Initialization
```{r}
set.seed(5)
v0 = 0.05
v1 = 10
beta = matrix(0.5,p,p)
diag(beta) = 0
#beta = rep(1,p)
sigma2 = 1
theta = runif(1)
nu = 1
lambda = 1
a = 1
b = 1
```

```{r}
iters = 1000
for (it in 1:iters) {
## E-step

ap = theta*dnorm(beta,0,sqrt(sigma2*v1))
bp = (1-theta)*dnorm(beta,0,sqrt(sigma2*v0))
prob = ap/(ap+bp)
d = ((1-prob)/v0+prob/v1)

## M-step
for (i in 1:p) {
  beta[i,-i] = solve(x[-i,]%*%t(x[-i,])+diag(as.vector(d[i,-i])),x[-i,]%*%(x[i,]))
}
#beta = solve(t(x)%*%x+diag(d),t(x)%*%y)
#beta = (diag(1/d)-diag(1/d)%*%t(x)%*%solve(matrix(1,n,n)+x%*%diag(1/d)%*%t(x),x%*%diag(1/d)))%*%t(x)%*%y
#sigma2= norm(y-x%*%beta,"2")^2+sum(d*beta^2)+nu*lambda
sigma2 = norm(x-beta%*%x,"F")^2+norm(beta^2*d,"F")^2+nu*lambda
sigma2 = sigma2/(p^2+n*p+nu)
#sigma2 = sigma2/(n+p+nu)
theta = (sum(prob)+a-1)/(a+b+p^2-2)
}
```
```{r}
plot(beta0,beta)
```